Task 8, 10, 11.
ivanrybin/itmo-hws-architecture pull request #6
Opened 2020-06-09 19:26 UTC by ivanrybin

2020-06-25 23:19 UTC, ottergottaott requested changes
Работа сырая и явно делалась в последний момент. 

Работа не командная, т.к. @Liza858 вообще никакого кода не написала, если верить коммитам. 

Из-за того, что работа некомандная, в диздоке нет диаграмм, которые бы описывали систему:

- Композиция (диаграмма компонентов)
- Логическая структура (диаграмма классов)
- Взаимодействия и состояния 
    - диаграммы последовательностей

Диаграмма состояний с двумя состояниями слишком скудная, терминал и игра -- это не состояния. Нужно переделать на что-то более подробноее, мб, для этого нужно выбрать какой-то другой процесс, не запуск/выход из игры.


Помимо этого требовалось:
- Карта должна на выбор пользователя случайно генерироваться или грузиться из файла

Нет юнит-тестов. 

И еще: если Вы сделали pr для проверки, то не нужно в него продолжать коммитить в течение еще 3 дней, делайте это в отдельную ветку, чтобы у проверяющего версия внезапно не начала отличаться в процессе проверки.

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/map/game_map.py
> +        self.py = player_start_y
Эти атрибуты нигде больше не будут использоваться, только для создания `Room` в этом же конструкторе. Лучше сразу передать `player_start_x`

Кажется, что `start_room` тоже можно попытаться убрать, т.к. его все равно кладем в `rooms`, т.е. он доступен везде.

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/map/game_map.py
> +                    self.cells[x][y].unblock()
Тут же совсем очевидное дублирование кода, избавьтесь от него

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/map/game_map.py
> +            self.create_room(room)
Точно также полностью скопированный метод.

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/map/game_map.py
> +            self.cells[x][y].block()
А зачем эти методы? Они нигде не используются

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/map/game_map.py
> +        self.state = State.PLAYER_TURN
Также не нашел использования `state`

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/strategy.py
> +
Код, пестрящий литералами, сложно читать. Даже, когда задаются всего две координаты.

Вы же понимаете, что здесь выбирается направление, в которое нужно сместить `self`, так и сделайте несколько объектов, которые можно передать в `update_pos`, так намного нагляднее будет:
```python
Vec2D = namedtuple('Point', ['x', 'y'])

class CowardStrategy(Strategy):
    UP = Vec2D(0, 1)
    UP_RIGHT = Vec2D(-1, 1)
    DOWN = Vec2D(0, -1)
    DOWN_LEFT = Vec2D(-1, -1)
    LEFT = Vec2D(-1, 0)
    ...

    @staticmethod
    def act(self, target, fov_map, game_map, mobs):
        info = []
        if tc.map_is_in_fov(fov_map, self.x, self.y):

            dist = self.get_dist(target)
            if 2 <= dist <= 5:
                if self.x - target.x < 0:
                    if self.y - target.y < 0:
                        self.update_pos(*CowardStrategy.DOWN_LEFT, game_map)
                    elif self.y - target.y == 0:
                        self.update_pos(*CowardStrategy.DOWN, game_map)
                    else:
                        self.update_pos(*CowardStrategy.UP_RIGHT, game_map)
    ...
```
Можно еще сделать так, чтобы `update_pos` получал `Vec2D`, тогда и распаковывать не придется.

Помимо этого не понятно почему именно `if 2 <= dist <= 5` такие константы

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/strategy.py
> +        return []
Зачем тут иерархия нужна не понятно, все равно никаких гарантий, что `act` будет определен, такая иерархия не дает. 

Сделайте так, чтобы гарантии появились

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/player.py
> +                         'UP': (0, -1), 'DOWN': (0, 1)}
Ага, вот тут внезапно вырастают направления

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/engine/engine.py
> +                        return self.player.move("RIGHT", self.map, self.entities)
И эти направления плохо сделаны, конечно. Передавать строковые литералы -- плохая идея, т.к. в них легко опечататься, мы не знаем какие точно можно, а какие нельзя и т.д. Лучше использовать вместо этого Enum

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/map/room.py
> +        super().__init__(*args, **kwargs)
Я не уверен есть ли смысл создавать отдельную иерархию для `Rectangle`. Убедите меня, что это необходимо или уберите

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/map/game_map.py
> +        self.state = State.PLAYER_TURN
Нашел, но все равно думаю, что ему тут не место

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/map/game_map.py
> +    def create_rooms(self, cnt=rnd.randint(5, 10), with_intersection=False):
Отмечу отдельно, что случайное значение в качестве аргумента по-умолчанию -- издевательство над человеком, который этот код будет использовать. 

Нужно либо выпилить, либо аккуратно описать в комментариях к методу каким образом будут выбираться аргументы. 

Еще и не совсем честный рандом получается: значение будет присвоено один раз при создании функции `create_room`.

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/engine/engine.py
> +        # служебные штуки
Этот комментарий бесполезен

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/engine/engine.py
> +        self.whos_state = State.PLAYER_TURN
Я уверен, что тут >10 атрибутов точно не нужно. 

Зачем константы объявляются для каждого объекта? Почему не вынести их в атрибуты класса?

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/engine/engine.py
> +    return int(value)
Серьезно? Зачем?

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/engine/engine.py
> +                                        pass
Бесполезный if

Начните замечать, пожалуйста, что Вы какое-то огромное количество вложенных блоков делаете. Тут уже 8. Читать такой код, конечно, очень сложно. 

Старайтесь не устраивать читающему когнитивную перегрузку на ровном месте, ему еще нужно догатываться что Вы тут имели ввиду. 3-4 вложенных блока -- максимум

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/engine/engine.py
> +                  debug=debug)
Я бы унес этот метод отсюда, кажется, что он не должен быть привязан к `engine`, а скорее привязан к месту, где будет использоваться (куда-то ближе к main).

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/player.py
> +        return info
Почему всегда `HEALTH_PIN` добавляет 5 очков здоровья? А если захотим сделать баночки с разным количеством HP? Будем тут код изменять?

Не понимаю почему `<..>.intox_start_time += 7`. Откуда взялась цифра 7?

Переменная с названием `info` не говорит вообще ни о чем. Объект, который Вы собрали, плохо получается описать словами, потому что непонятно что это за объект и какими свойствами он должен обладать. 

Попробуйте как-то от "произвольный список со словариками внутри" уйти к чему-то более конкретному, тогда и нормальное название найдется

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/player.py
> +            return []
Вообще это нужно где-то выше было спросить, но спрошу тут. С чего вдруг `game_map` держит текущее состояние игры, в котором отражается чей ход?

Кажется, что карта -- это набор клеток, мб, каких-то сущностей на карте типа стен и комнат, но ничего более. 

Попытка пропихнуть туда `state` похожа на попытку завести глобальное состояние, подумайте как от этого можно избавиться

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/mob.py
> +            for i in range(0, 5):
Почему именно 5? Снова хардкод

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/entity.py
> +            self.char = ord(char)
Не использованные переменные

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/entity.py
> +        self.main_color = color
Тут опять какие-то километры переменных, уверен, что больше половины из них можно без особого вреда выпилить.

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/entity.py
> +            self.y = 0
Код подозрительно похож. Мб, можно обобщить

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/entity.py
> +    return None
??? 

Почему это не метод класса, если тут self есть?

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/inventory.py
> +        return info
Тут с возвращаемым значением тоже фигня какая-то. Почему `Inventory` должен знать какое сообщение нужно вернуть, если в нем нет предмета? 

Кажется, это совсем не его ответственность, а из функции нужно либо boolean вернуть, либо сам `item_entity`

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/README.md
> +    Может запуститься не с первой попытки (баг в рандомной генерации карты)
:)

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/engine/serialization.py
> +        json.dump(data, file, indent=4)
А почему не использовать pickle вместо собирания json ручками?

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/engine/serialization.py
> +
Код дублируется с `init_item` из `get_player_from_stats`

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/engine/serialization.py
> +        'GAME_NAME': engine.GAME_NAME
Мне кажется, что тут очень много перекладываний из одних словарей в другие и это можно обойти, если бы объекты, которыми Вы тут жонглируете, сами были ответственны за сериализацию/десериализацию

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/patterns/command.py
> +        return self.func(*self.args, **self.kwargs)
Расскажите чем это от обычной лямбды с замыканием отличается и почему нельзя использовать ее вместо `Command`?

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/patterns/decorator.py
> +    player.color = tc.fuchsia
Сделайте обычный декоратор, не питонячий. Чтобы не было изменений объекта, который сюда передали. 

Идея декоратора в том, чтобы можно было динамически _добавить_ функциональность существующему объекту, но не изменять его.

2020-06-25 23:19 UTC, ottergottaott commented on roguelike/project/logic/patterns/decorator.py
> +    def drunk_move(self, move_type, game_map, mobs):
Еще и декораторы так и не научились писать. `functools.wraps`?

2020-06-25 23:19 UTC, aleksZubakov commented on roguelike/project/engine/engine.py
> +    def run(self):
В `run`  слишком много всего происходит, постарайтесь разбить.

Скорее всего можно `engine` разбить на несколько классов и разнести ответственности, попробуйте это сделать.

2020-06-26 18:40 UTC, ivanrybin commented on roguelike/project/map/game_map.py
> +        self.py = player_start_y
Исправлено.

run разбит на player_turn() и mob_turn().

Engine разбит на Engine, EngineInitializer, KeysHandler.

2020-06-26 18:40 UTC, ivanrybin commented on roguelike/project/map/game_map.py
> +                    self.cells[x][y].unblock()
Исправлено.

2020-06-26 18:40 UTC, ivanrybin commented on roguelike/project/map/game_map.py
> +            self.create_room(room)
Исправлено.

2020-06-26 18:40 UTC, ivanrybin commented on roguelike/project/map/game_map.py
> +            self.cells[x][y].block()
Исправлено.

2020-06-26 18:41 UTC, ivanrybin commented on roguelike/project/map/game_map.py
> +        self.state = State.PLAYER_TURN
Исправлено.

Перенесено в `engine.curr_state, engine.prev_state`.

2020-06-26 18:42 UTC, ivanrybin commented on roguelike/project/logic/strategy.py
> +
Исправлено.

Литералы заменены атрибутами. Добавлены `Vec2D`. В` update_pos` подаются сами объекты без ракскрытия.

2020-06-26 18:44 UTC, ivanrybin commented on roguelike/project/logic/strategy.py
> +        return []
Исправлено.

Иерархия убрана. Гарантия, если правильно понял, заключается в наличии метода. Теперь каждая стратегия не переопределяет act, а дает свой => нет стратегии = exception.

2020-06-26 18:44 UTC, ivanrybin commented on roguelike/project/logic/player.py
> +                         'UP': (0, -1), 'DOWN': (0, 1)}
Исправлено, см. выше.

2020-06-26 18:44 UTC, ivanrybin commented on roguelike/project/engine/engine.py
> +                        return self.player.move("RIGHT", self.map, self.entities)
Исправлено, добавлен Enum, см. выше.

2020-06-26 18:45 UTC, ivanrybin commented on roguelike/project/map/room.py
> +        super().__init__(*args, **kwargs)
Исправлено.

`Rectangle ` удален.

2020-06-26 18:45 UTC, ivanrybin commented on roguelike/project/map/game_map.py
> +    def create_rooms(self, cnt=rnd.randint(5, 10), with_intersection=False):
Исправлено на атрибут класса.

2020-06-26 18:45 UTC, ivanrybin commented on roguelike/project/engine/engine.py
> +        # служебные штуки
Удален.

2020-06-26 18:46 UTC, ivanrybin commented on roguelike/project/engine/engine.py
> +        self.whos_state = State.PLAYER_TURN
Исправлено. 

Спрятано в `EngineInfo`. Константы нужны.

2020-06-26 18:46 UTC, ivanrybin commented on roguelike/project/engine/engine.py
> +    return int(value)
Незачем, удалено.

2020-06-26 18:46 UTC, ivanrybin commented on roguelike/project/engine/engine.py
> +                                        pass
Удален.

2020-06-26 18:47 UTC, ivanrybin commented on roguelike/project/engine/engine.py
> +                  debug=debug)
Исправлено. 

Перенесен в `game_starter.py`.

2020-06-26 18:48 UTC, ivanrybin commented on roguelike/project/logic/player.py
> +        return info
Исправлено на атрибуты соответствующих предметов.

От словаря ушел к `OperationLog`.

2020-06-26 18:48 UTC, ivanrybin commented on roguelike/project/logic/player.py
> +            return []
Исправлено. 

`engine` держит вместо `game_map`.

2020-06-26 18:49 UTC, ivanrybin commented on roguelike/project/logic/mob.py
> +            for i in range(0, 5):
Исправлено на атрибут класса.

2020-06-26 18:49 UTC, ivanrybin commented on roguelike/project/logic/entity.py
> +            self.char = ord(char)
Нет, эти переменные определяют символ сущности на карте, они нужны.

2020-06-26 18:49 UTC, ivanrybin commented on roguelike/project/logic/entity.py
> +        self.main_color = color
Нельзя.

2020-06-26 18:49 UTC, ivanrybin commented on roguelike/project/logic/entity.py
> +            self.y = 0
Обобщен.

2020-06-26 18:50 UTC, ivanrybin commented on roguelike/project/logic/entity.py
> +    return None
Исправлено, теперь метод класса.

2020-06-26 18:50 UTC, ivanrybin commented on roguelike/project/logic/inventory.py
> +        return info
Не согласен. Хочу, чтобы было так.

2020-06-26 18:50 UTC, ivanrybin commented on roguelike/README.md
> +    Может запуститься не с первой попытки (баг в рандомной генерации карты)
(:

2020-06-26 18:51 UTC, ivanrybin commented on roguelike/project/engine/serialization.py
> +        'GAME_NAME': engine.GAME_NAME
Исправлено.

За сериализацию каждый объект отвечает сам.
С десериализацией не получилось, поскольку образуются циклические зависимости подключаемых пакетов, но функции переписал на куда более приятные.

2020-06-26 18:52 UTC, ivanrybin commented on roguelike/project/logic/patterns/command.py
> +        return self.func(*self.args, **self.kwargs)
Ничем, это реализация паттерна "Команда", который некуда положить.

2020-06-26 18:53 UTC, ivanrybin commented on roguelike/project/logic/patterns/decorator.py
> +    player.color = tc.fuchsia
Исправлено, но не на декоратор пользователя, а на декоратор обработчика движения пользователя, поскольку иначе пришлось бы переопределять очень много.

2020-06-26 18:54 UTC, ivanrybin commented on roguelike/project/engine/engine.py
> +    def run(self):
Исправлено, см. выше.

2020-06-26 18:59 UTC, ivanrybin commented
> Работа не командная, т.к. @Liza858 вообще никакого кода не написала, если верить коммитам.
В заголовке PR две фамилии, работа командная.

> Из-за того, что работа некомандная, в диздоке нет диаграмм, которые бы описывали систему:
Лиза пока не успела сделать диаграммы. Все будет. 

> Карта должна на выбор пользователя случайно генерироваться или грузиться из файла
Исправлено. Добавлена возможность подгрузить SD-map.

> Нет юнит-тестов. 
В требованиях юнит-тесты не указаны, непонятно, что тестировать, если результат на экране.

> И еще: если Вы сделали pr для проверки, то не нужно в него продолжать коммитить в течение еще 3 дней
Спасибо, учту в следующих задачах.

2020-06-30 23:59 UTC, ottergottaott requested changes
В таком виде не могу засчитать, исправляйте

2020-06-30 23:59 UTC, ottergottaott commented on roguelike/project/map/game_map.py
> +    def __init__(self, width, height, player_start_x, player_start_y, load_type='NORMAL'):
Расскажите почему передача `load_type` в виде строки вместо значения `enum` --  плохо

2020-06-30 23:59 UTC, ottergottaott commented on roguelike/project/engine/engine.py
> +            for mob in self.entities[1:]:
А с чего тут мы знаем, что в `entities` начиная с индекса 1 лежат мобы?

Если нужно это знание протащить и разделять мобов от кого-то еще (видимо, игрока), то и заведите две отдельные перменные.

2020-06-30 23:59 UTC, ottergottaott commented on roguelike/project/engine/engine.py
> +                operation_log = mob.act(self.player, self.fov, self.map, self.entities)
Все еще очень странная абстракция. Почему лог возвращается в случае успешности действия и почему это проверяется каким-то очень странным способом: `if ... and  operation_log.log`

2020-06-30 23:59 UTC, aleksZubakov commented on roguelike/project/engine/engine.py
> +                                self.curr_state.value = State.PLAYER_DEAD
Дважды присваивается один атрибут. Это хоть сколько-то осмыслено? Если нет, то давайте сделаем так, что `kill_player` будет возвращать `message`. 

А лучше просто создадим message сами на вызывающей стороне.

2020-06-30 23:59 UTC, aleksZubakov commented on roguelike/project/engine/engine.py
> +                                self.curr_state.value = State.PLAYER_DEAD
Если это сделать + вынести методы и инвертировать некоторые условия, можно улучшить код:

```python
def mob_turn(self):
    if self.curr_state.value != State.MOB_TURN:
        return

    # обновление поведения сущности, если она бот
    _, *mobs = self.entities
    for mob in mobs:
        operation_log = mob.act(self.player, self.fov, self.map, self.entities)

        if not operation_log or not operation_log.log:
            continue

        for item in operation_log.log:
            message = item.get('message')
            if message:
                self.info.msg_log.add_message(message)

            maybe_dead_entity = item.get('dead')
            if maybe_dead_entity:
                message = self.kill(maybe_dead_entity)
                self.info.msg_log.add_message(message)

    if self.curr_state.value != State.PLAYER_DEAD:
        self.curr_state.value = State.PLAYER_TURN

def kill(self, entity):
    if isinstance(entity, Player):
        self.curr_state.value = State.PLAYER_DEAD
        return kill_player(entity)
    else:
        return kill_mob(entity)
```

Можно еще унести возню при смерти какой-то штуки внутрь, тогда `self.kill(maybe_dead_entity)` превратится в `maybe_dead_entity.die() и метод `self.kill` можно будет выкинуть.

2020-06-30 23:59 UTC, aleksZubakov commented on roguelike/project/engine/engine.py
> +    def run(self):
Все еще громоздкие функции, которые сложно читать

2020-06-30 23:59 UTC, aleksZubakov commented on roguelike/project/engine/keys_handler.py
> +                                       engine.map, engine.entities, engine.curr_state)
А теперь заметьте, что все `Command` отличаются только в одном аргументе.

Вынесите создание `Command` в отдельный метод

2020-06-30 23:59 UTC, aleksZubakov commented on roguelike/project/logic/entity.py
> +        self.main_color = color
Например, зачем `inventory` мобам? Почему этот атрибут не мог быть объявлен только в `Player`?

Один `item` может быть только у моба, `Player` это не нужно.

> Нельзя.

Так это не работает. Если считаете, что нельзя, то необходимо аргументировать почему.

Пока вижу, что это можно и нужно исправить.

Это же относится к сообщению откуда-то ниже
> Не согласен. Хочу, чтобы было так.

2020-06-30 23:59 UTC, aleksZubakov commented on roguelike/project/logic/entity.py
> +        self.main_color = color
К слову, что будете делать, если вдруг захотим сделать босса, из которого должно падать 5 item-ов?

2020-06-30 23:59 UTC, aleksZubakov commented on roguelike/project/logic/patterns/strategy.py
> +    @abstractmethod
Учитесь читать документацию. Там про `abstractmethod` пишут такое::

    Using this decorator requires that the class’s metaclass is ABCMeta or is derived from it. 
    A class that has a metaclass derived from ABCMeta cannot be instantiated unless all of its 
    abstract methods and properties are overridden. The abstract methods can be called using
    any of the normal ‘super’ call mechanisms. abstractmethod() may be used to declare 
    abstract methods for properties and descriptors.

2020-07-02 08:59 UTC, Liza858 commented on roguelike/project/engine/engine.py
> +            for mob in self.entities[1:]:
исправила

2020-07-02 09:02 UTC, Liza858 commented on roguelike/project/engine/engine.py
> +                operation_log = mob.act(self.player, self.fov, self.map, self.entities)
Лог возвращается не в случае успешности действия, а всегда. То есть при выполнении каких-то действий 
собирается лог событий, он и возвращается. А проверка и не нужна, можно просто идти по operation_log.log в цикле. Если operation_log.log == [ ], то просто ничего не произойдет.

2020-07-02 09:03 UTC, Liza858 commented on roguelike/project/engine/engine.py
> +                                self.curr_state.value = State.PLAYER_DEAD
Исправила. Добавила игроку и мобу метод die(), который возвращает message.

2020-07-02 09:03 UTC, Liza858 commented on roguelike/project/engine/keys_handler.py
> +                                       engine.map, engine.entities, engine.curr_state)
исправила

2020-07-02 09:05 UTC, Liza858 commented on roguelike/project/logic/patterns/strategy.py
> +    @abstractmethod
исправила. теперь:

class Strategy(ABC):

    @abstractmethod
    def act(self, *args, **kwargs):
        pass

2020-07-02 09:08 UTC, Liza858 commented on roguelike/project/engine/engine.py
> +    def run(self):
Разбила run: вынесла действия, которые совершаются после окончания игры в отдельную функцию -- game_exit()

2020-07-02 09:10 UTC, Liza858 commented on roguelike/project/logic/inventory.py
> +        return info
add_item теперь возвращает boolean

2020-07-02 09:13 UTC, Liza858 commented on roguelike/project/logic/entity.py
> +        self.main_color = color
Исправила. Теперь inventory есть только у игрока, а strategy только у моба. 
item тоже есть только у моба.

2020-07-02 09:14 UTC, Liza858 commented on roguelike/project/logic/entity.py
> +        self.main_color = color
если захотим сделать босса, то тогда нужно будет сделать, чтобы у моба был список item-ов.

2020-07-02 09:20 UTC, Liza858 commented on roguelike/project/map/game_map.py
> +    def __init__(self, width, height, player_start_x, player_start_y, load_type='NORMAL'):
Потому что тот, кто читает код должен понимать из какого набора возможных значений взята константа.
Еще в литерале можно опечататься и, возможно, ошибку будет сложно отследить.

2020-07-02 09:20 UTC, Liza858 commented on roguelike/project/map/game_map.py
> +    def __init__(self, width, height, player_start_x, player_start_y, load_type='NORMAL'):
Исправила. Теперь везде используются константы из EngineLoadTypes.

2020-07-08 00:32 UTC, aleksZubakov commented on roguelike/project/engine/engine.py
> +            for mob in self.entities[1:]:
Но все еще мобы и игрок находятся в одном `entities`

2020-07-08 00:32 UTC, aleksZubakov commented on roguelike/project/engine/engine.py
> +                operation_log = mob.act(self.player, self.fov, self.map, self.entities)
> А проверка и не нужна

Если не нужна то уберите ее, почему-то осталась.

2020-07-08 00:37 UTC, aleksZubakov commented on roguelike/project/logic/entity.py
> +        self.type = entity_type
Зачем `type` нужен?

2020-07-08 16:19 UTC, Liza858 commented on roguelike/project/engine/engine.py
> +            for mob in self.entities[1:]:
Я подумала, что вы имеете  в виду -- разделить их в методе.
Исправила, теперь есть self.player и self.mobs

2020-07-08 16:19 UTC, Liza858 commented on roguelike/project/engine/engine.py
> +                operation_log = mob.act(self.player, self.fov, self.map, self.entities)
Теперь убрала

2020-07-08 16:21 UTC, Liza858 commented on roguelike/project/logic/entity.py
> +        self.type = entity_type
Он использовался для проверки типа item у моба, что бессмысленно, так как посмотреть тип у item можно как 
item.type. 

Вообще убрала это поле.

2020-07-09 15:44 UTC, aleksZubakov commented on roguelike/project/logic/entity.py
> +        self.type = entity_type
Не очень хорошо, что приходится на это указывать. Учитесь самостоятельно обращать внимание на такие вещи.

2020-07-09 15:45 UTC, aleksZubakov commented
Работу засчитываю

2020-07-11 09:14 UTC, merged